export const GOT_ETH_ACCOUNT = "GOT_ETH_ACCOUNT";
export const GOT_CRYPTOMONS = "GOT_CRYPTOMONS";
export const GOT_OWNED_TOKENS = "GOT_OWNED_TOKENS";
export const GOT_EXITING_FROM = "GOT_EXITING_FROM";
export const GOT_CONTRACTS = "GOT_CONTRACTS";
export const GOT_CHALLENGEABLES = "GOT_CHALLENGEABLES";